name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cargo-vcpkg
        run: cargo install cargo-vcpkg
     
      - name: Install yasm (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install yasm libasound2-dev

      - name: Install yasm (Darwin)
        if: matrix.os == 'macos-latest'
        run: brew install yasm

      - name: Install dependencies
        run: cargo vcpkg -v build

      - name: Build
        shell: bash
        run: |
          set -xeuo pipefail
          rustc --version
          cargo --version
          deno_bindgen --release -- --features "use-vcpkg"

      - name: Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release draft"
          draft: true
          files: |
            target/release/libdeno_sdl2.so
            target/release/libdeno_sdl2.dylib
            target/release/deno_sdl2.dll
